server:
  port: 8090
  servlet:
    context-path: /d-una/api/v1
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    root: INFO
